#!/usr/bin/env python3
"""Render everything derived from docker/images.json.

``images.json`` is the single source of truth for which MCP server lives in
which environment and container image. This script projects it into the
consumers that would otherwise drift out of sync:

``servers``
    ``venv/servers.tsv``, the table ``venv/run --server <name>`` reads to find a
    server's uv project, module and image. Tab-separated on purpose: the
    launcher is bash and must not need a Python interpreter or jq to start.

``server-map <image>``
    A ``server:env:module`` table baked into each image and read by
    ``docker/entrypoint.sh``, so ``docker run -i <image> <server>`` works.

``plugin-mcp``
    The ``mcpServers`` block for ``.claude-plugin/plugin.json``. Every server
    goes through ``venv/run``, which picks uv or a container runtime.

``matrix``
    The GitHub Actions build matrix, one entry per (image, platform).

``servers`` and ``plugin-mcp`` write their files in place unless ``--stdout``
is given, and ``--check`` exits non-zero when the committed file is stale.

Usage:
    python docker/render.py servers [--check]
    python docker/render.py plugin-mcp [--check]
    python docker/render.py server-map cpu
    python docker/render.py matrix

Requirements:
    - Python 3.10+, standard library only
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
IMAGES_SPEC = PROJECT_ROOT / "docker" / "images.json"
PLUGIN_MANIFEST = PROJECT_ROOT / ".claude-plugin" / "plugin.json"
SERVERS_TABLE = PROJECT_ROOT / "venv" / "servers.tsv"

# Marks a server that has no uv project and runs only from its image.
CONTAINER_ONLY = "-"


def load_spec() -> dict:
    """Return the parsed image specification."""
    return json.loads(IMAGES_SPEC.read_text())


def find_image(spec: dict, name: str) -> dict:
    """Return the image entry called ``name``, or exit with the valid names."""
    for image in spec["images"]:
        if image["name"] == name:
            return image
    valid = ", ".join(i["name"] for i in spec["images"])
    sys.exit(f"unknown image {name!r}; expected one of: {valid}")


def normalise_servers(image: dict) -> dict[str, dict]:
    """Return ``{server: {env, module}}`` for either build strategy.

    A uv image installs exactly one uv project, named by ``venv``, and maps
    servers straight to modules. A conda-lock image carries one conda env per
    server and spells both out.
    """
    out = {}
    for server, value in image["servers"].items():
        if isinstance(value, str):
            out[server] = {"env": image["venv"], "module": value}
        else:
            out[server] = {"env": value["env"], "module": value["module"]}
    return out


def servers_table(spec: dict) -> str:
    """Return the text of venv/servers.tsv."""
    lines = [
        "# Generated by docker/render.py servers from docker/images.json -- do not edit.",
        "# server\tvenv\tmodule\timage\tgpu\tplatforms",
        "# venv is the uv project under venv/, or '-' when the server has none and",
        "# runs only from its container image.",
    ]
    rows = []
    for image in spec["images"]:
        for server, info in normalise_servers(image).items():
            venv = image["venv"] if image["build"] == "uv" else CONTAINER_ONLY
            rows.append(
                "\t".join(
                    [
                        server,
                        venv,
                        info["module"],
                        image["name"],
                        "1" if image["gpu"] else "0",
                        ",".join(image["platforms"]),
                    ]
                )
            )
    return "\n".join(lines + sorted(rows)) + "\n"


def write_or_check(path: Path, text: str, args: argparse.Namespace, regen: str) -> int:
    """Print, check, or write a rendered file."""
    if args.stdout:
        sys.stdout.write(text)
        return 0
    if args.check:
        current = path.read_text() if path.exists() else ""
        if current != text:
            print(f"{path.relative_to(PROJECT_ROOT)} is stale; run: {regen}")
            return 1
        print(f"{path.relative_to(PROJECT_ROOT)} is up to date")
        return 0
    path.write_text(text)
    print(f"Wrote {path.relative_to(PROJECT_ROOT)}")
    return 0


def cmd_servers(spec: dict, args: argparse.Namespace) -> int:
    """Write (or check) venv/servers.tsv."""
    return write_or_check(
        SERVERS_TABLE, servers_table(spec), args, "python docker/render.py servers"
    )


def cmd_server_map(spec: dict, args: argparse.Namespace) -> int:
    """Print the shell-parseable server table for one image."""
    image = find_image(spec, args.image)
    env_vars = image.get("env_vars", {})
    lines = [
        "# server:env:module[:KEY=VAL,KEY=VAL]",
        f"# generated from docker/images.json for image {image['name']}",
    ]
    for server, info in sorted(normalise_servers(image).items()):
        row = f"{server}:{info['env']}:{info['module']}"
        extra = env_vars.get(server)
        if extra:
            row += ":" + ",".join(f"{k}={v}" for k, v in sorted(extra.items()))
        lines.append(row)
    print("\n".join(lines))
    return 0


def per_platform(image: dict, key: str, platform: str, default):
    """Return a setting that may be either shared or keyed by platform."""
    value = image.get(key, default)
    if isinstance(value, dict):
        return value.get(platform, default)
    return value


def cmd_matrix(spec: dict, args: argparse.Namespace) -> int:
    """Print the GitHub Actions matrix as JSON, one entry per image+platform."""
    runner = {"linux/amd64": "ubuntu-24.04", "linux/arm64": "ubuntu-24.04-arm"}
    subdir = {"linux/amd64": "linux-64", "linux/arm64": "linux-aarch64"}
    include = []
    for image in spec["images"]:
        for platform in image["platforms"]:
            if image["build"] == "uv":
                dockerfile = "docker/Dockerfile"
                build_args = {"VENV": image["venv"], "IMAGE_NAME": image["name"]}
            else:
                dockerfile = "docker/Dockerfile.cuda"
                build_args = {
                    "IMAGE_NAME": image["name"],
                    "CONDA_ENVS": " ".join(image["envs"]),
                    "CONDA_SUBDIR": subdir[platform],
                    "PYG_FROM_SOURCE": (
                        "1"
                        if per_platform(image, "pyg_from_source", platform, False)
                        else "0"
                    ),
                    "TORCH_CUDA_ARCH_LIST": per_platform(
                        image, "torch_cuda_arch_list", platform, "12.1"
                    ),
                    "CONDA_ENV_PYTHON": " ".join(
                        f"{env}={py}" for env, py in image.get("env_python", {}).items()
                    ),
                    "PIP_EXTRA_INDEX_URL": (
                        ""
                        if platform == "linux/amd64"
                        else "https://download.pytorch.org/whl/cu130"
                    ),
                }
            include.append(
                {
                    "image": image["name"],
                    "platform": platform,
                    "arch": platform.split("/")[1],
                    "runner": runner[platform],
                    "dockerfile": dockerfile,
                    "build_args": build_args,
                    "gpu": image["gpu"],
                    "servers": " ".join(sorted(image["servers"])),
                    # Only images built for more than one platform need a
                    # manifest list stitched together afterwards.
                    "multiarch": len(image["platforms"]) > 1,
                }
            )
    print(json.dumps({"include": include}))
    return 0


def plugin_servers(spec: dict) -> dict[str, dict]:
    """Return the plugin manifest's mcpServers block.

    Every server goes through venv/run rather than an inline command: whether a
    server runs from a uv project on the host or from a container image depends
    on what the host supports, and one static argument list cannot express
    that. The launcher decides; configuration reaches it through env.

    ATOMISTIC_WORKSPACE pins the servers to the project Claude Code was opened
    in -- the same directory skill scripts run in -- so a path one of them
    writes is a path the other can read.
    """
    servers: dict[str, dict] = {}
    for image in spec["images"]:
        for server in sorted(normalise_servers(image)):
            servers[server] = {
                "command": "${CLAUDE_PLUGIN_ROOT}/venv/run",
                "args": ["--server", server],
                "env": {
                    "ATOMISTIC_RUNTIME": "${user_config.runtime}",
                    "ATOMISTIC_IMAGE_REGISTRY": "${user_config.image_registry}",
                    "ATOMISTIC_IMAGE_TAG": "${user_config.image_tag}",
                    "ATOMISTIC_WORKSPACE": "${CLAUDE_PROJECT_DIR}",
                },
            }
    return dict(sorted(servers.items()))


def cmd_plugin_mcp(spec: dict, args: argparse.Namespace) -> int:
    """Write (or print, or check) the plugin manifest's mcpServers block."""
    servers = plugin_servers(spec)
    if args.stdout:
        print(json.dumps({"mcpServers": servers}, indent=2))
        return 0
    manifest = json.loads(PLUGIN_MANIFEST.read_text())
    if args.check:
        if manifest.get("mcpServers") != servers:
            print(
                "plugin.json mcpServers is stale relative to docker/images.json; "
                "run: python docker/render.py plugin-mcp"
            )
            return 1
        print(f"plugin.json mcpServers matches images.json ({len(servers)} servers)")
        return 0
    manifest["mcpServers"] = servers
    PLUGIN_MANIFEST.write_text(json.dumps(manifest, indent=2) + "\n")
    print(
        f"Wrote {len(servers)} servers to {PLUGIN_MANIFEST.relative_to(PROJECT_ROOT)}"
    )
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    sub = parser.add_subparsers(dest="cmd", required=True)

    for name, func, help_text in (
        ("servers", cmd_servers, "venv/servers.tsv for venv/run"),
        ("plugin-mcp", cmd_plugin_mcp, "mcpServers block for plugin.json"),
    ):
        p = sub.add_parser(name, help=help_text)
        mode = p.add_mutually_exclusive_group()
        mode.add_argument(
            "--stdout", action="store_true", help="print instead of writing"
        )
        mode.add_argument(
            "--check", action="store_true", help="fail if the file is stale"
        )
        p.set_defaults(func=func)

    p = sub.add_parser("server-map", help="shell table of servers for one image")
    p.add_argument("image", help="image name from docker/images.json")
    p.set_defaults(func=cmd_server_map)

    p = sub.add_parser("matrix", help="GitHub Actions build matrix as JSON")
    p.set_defaults(func=cmd_matrix)

    args = parser.parse_args()
    return args.func(load_spec(), args)


if __name__ == "__main__":
    sys.exit(main())
